trigger:
  branches:
    include:
    - main
  paths:
    include:
    - modules/AzureVirtualMachines/* #Changepath

pool:
  vmImage: 'windows-2019'  #Change if needed

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      Install-Module -Name Az.Accounts -Force -AllowClobber -Scope CurrentUser
      Install-Module -Name Az.Compute -Force -AllowClobber -Scope CurrentUser
      $Module = Get-Module -Name Az.Accounts, Az.Compute -ListAvailable
      if (-not $Module) {
        Write-Error "Failed to install Az modules"
        Exit 1
      }

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      
      Import-Module PowerShellGet -Force #Import the PowerShellGet module (Ensure you are not using alias...)
      
      $modulePath = "modules/AzureVirtualMachines"

      Publish-Module -Path $modulePath -NuGetApiKey "$(PowerShellGalleryApiKey)" -Force -Verbose ; Start-Sleep -Seconds 10
  displayName: 'Publish Module to PowerShell Gallery'