trigger:
  branches:
    include:
    - main
  paths:
    include:
    - modules/graph/* #Change path

pool:
  vmImage: 'windows-2019'  #Change if needed

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      Install-Module -Name MSAL.PS -Force -AllowClobber -Scope CurrentUser
      Install-Module -Name AzureSecrets -Force -AllowClobber -Scope CurrentUser
      $Module = Get-InstalledModule -Name AzureSecrets, MSAL.PS
      if (-not $Module) {
        Write-Error "Failed to install modules"
        Exit 1
      }

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      
      Import-Module PowerShellGet -Force #Import the PowerShellGet module (Ensure you are not using alias...)
      
      $modulePath = "modules/graph"

      Publish-Module -Path $modulePath -NuGetApiKey "$(PowerShellGalleryApiKey)" -Force -Verbose ; Start-Sleep -Seconds 10
  displayName: 'Publish Module to PowerShell Gallery'